#!/usr/bin/env python3

# import the client so that the bytecode compiled
# version is used on subsequent invocations

import husk_cli

if __name__ == "__main__":

    try:
        husk_cli.run()
    except Exception as e:
        print(e)

